name: Create and publish Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RUST_VERSION: 1.67.1

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - arch: amd64
            sha256: dead07b4d8ed7e29e98de0f4504d87e8880d4347859d839686a31da35a3b532f
          - arch: aarch64
            sha256: 73f11afcbb50d8bc70eab9f0850b3fa30e61a419bc48cf426e63527d14a8373b
          - arch: ppc64le
            sha256: b98bfc4a7094a98ed52d49f9558bb15a4cee9854f182d30085d459d4a55d2e03

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build and push Docker image
        run: |
          export IMAGE_TAG="$REGISTRY/$IMAGE_NAME:$RUST_VERSION-${{ matrix.target.arch }}"
          echo "Building image $IMAGE_TAG"
          docker build \
            --build-arg SHA=${{ matrix.target.sha256 }} \
            --build-arg RUST_VERSION=$RUST_VERSION \
            -t $IMAGE_TAG .
          docker push $IMAGE_TAG
